# Generated by Django 4.0.4 on 2022-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
